 require 'open-uri' #urlにアクセスできるようにする
 require 'kconv' #文字コード変換。文字化け対策
 require 'nokogiri'
 require 'csv'
 
  namespace :scrape do
   
   #task :sample_title => :environment do #開発環境のみ実行
   task :sample_title => :production do
  #(1..300).each do |i|
    #Url.create!(url: "https://www.weblio.jp/category/dictionary/aa/#{i}")
  #end
  
  urls = []
  (1..29).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/oo/#{i}",)
  end
  (1..26).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/aa/#{i}",)
  end
  (1..25).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/ii/#{i}",)
  end
  (1..17).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/uu/#{i}",)
  end
  (1..10).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/ee/#{i}",)
  end
  (1..4).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/ii-nn/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ee-nn/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-oo/#{i}")
  end
  (1..3).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/aa-ii/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ii-tsu/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-shi/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-mo/#{i}")
  end
  (1..2).each do |i|
    urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/aa-ku/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/aa-tsu/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/aa-ra/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/aa-nn/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ii-ii/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ii-ki/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ii-ta/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ii-chi/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/uu-ee/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/uu-tsu/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/uu-ra/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/ee-ii/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-ii/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-uu/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-ku/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-to/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-ri/#{i}",
                     "https://thesaurus.weblio.jp/category/nwnts/oo-nn/#{i}")
  end
  
  urls = urls.push("https://thesaurus.weblio.jp/category/nwnts/aa-aa",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-uu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ee",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-oo",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ka",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ki",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ke",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ko",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-sa",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-shi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-su",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-se",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-so",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ta",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-chi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-te",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-to",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-na",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ni",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-nu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ne",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-no",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-hi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-fu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-he",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ho",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ma",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-mi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-mu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-me",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-mo",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ya",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-yu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ri",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ru",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-re",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ro",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-wa",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ga",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-gi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-gu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ge",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-go",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-za",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-zi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-zu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ze",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-da",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-de",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-do",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-ba",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-bi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-bu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-be",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-bo",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-pa",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-pi",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-pu",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-pe",
                   "https://thesaurus.weblio.jp/category/nwnts/aa-po",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-aa",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-uu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ee",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-oo",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ka",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ku",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ke",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ko",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-sa",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-shi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-su",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-se",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-so",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-te",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-to",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-na",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ni",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-nu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ne",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-no",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ha",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-hi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-fu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-he",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ho",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ma",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-mi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-mu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-me",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-mo",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ya",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-yo",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ra",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ri",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ru",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-re",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ro",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-wa",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ga",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-gi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-gu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ge",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-go",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-za",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-zi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-zu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ze",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-zo",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-da",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-de",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-do",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-ba",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-bi",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-bu",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-be",
                   "https://thesaurus.weblio.jp/category/nwnts/ii-bo",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-aa",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ii",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-uu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-oo",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ka",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ki",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ku",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ke",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ko",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-sa",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-shi",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-su",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-se",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-so",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ta",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-chi",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-te",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-to",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-na",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ni",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-nu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ne",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-no",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ha",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-hi",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-he",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ma",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-mi",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-mu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-me",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-mo",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ya",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-yo",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ri",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ru",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-re",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ro",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-wa",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-nn",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ga",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-gu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ge",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-go",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-za",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-zi",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-zu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-zo",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-da",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-de",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-do",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-ba",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-bu",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-be",
                   "https://thesaurus.weblio.jp/category/nwnts/uu-bo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-aa",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-uu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ee",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ka",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ki",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ku",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ko",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-shi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-su",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-se",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-so",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ta",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-chi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-tsu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-te",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-to",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-na",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ni",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ne",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-no",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ha",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-fu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ho",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ma",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-mi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-mu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-me",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-mo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-yo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ra",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ri",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ru",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-re",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ro",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-wo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ga",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-gu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ge",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-go",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-za",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-zi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-zu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-zo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-da",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-de",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-do",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-ba",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-bi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-bu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-be",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-bo",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-pi",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-pu",
                   "https://thesaurus.weblio.jp/category/nwnts/ee-po",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-aa",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ee",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ka",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ki",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ke",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ko",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-sa",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-su",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-se",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-so",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ta",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-chi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-tsu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-te",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-na",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ni",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ne",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-no",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ha",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-hi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-fu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-he",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ma",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-mi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-mu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-me",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ya",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-yo",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ra",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ru",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-re",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ro",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-wa",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ga",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-gi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-gu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-go",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-za",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-zi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-zu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ze",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-zo",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-da",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-du",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-de",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-do",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-ba",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-bi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-bu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-be",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-bo",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-pa",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-pi",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-pu",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-pe",
                   "https://thesaurus.weblio.jp/category/nwnts/oo-po"
                   )
  

      
     urls.each do |url|
       html = open(url) do |f|
         f.read
       end
    
     doc = Nokogiri::HTML.parse(html,nil,'utf-8')
     
       doc.css('a.crosslink').each do |content|
         title = content.inner_text
         feed = Feed.new(
         title: title
         )
         feed.save
       end
     end
   end
 end

#bundle exec rake scrape:sample_title